# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

# используем режим обычного пользователя для сборки проекта.
sudo: false
env:
  global:
    - CODECOV_TOKEN="44f680bf-7130-494a-bb42-2a0ceb7ac0aa"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -klokovstas2013@gmail.com
    on_success: never # default: change
    on_failure: always # default: always